### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by promontis** [vpenades/SharpGLTF#1]
Hi @vpenades! Me again :)

Could you setup a NuGet package for this repository?
I would create one using https://www.myget.org/opensource

**Comment by vpenades** [comment]
I was planning to do it along next week.

Let me add some additional tests and do a final review of the API and I'll publish it

**Comment by vpenades** [comment]
Considering these issues before publishing:

- Assembly name and namespace: might change it to gltf4sharp... Mainly for disambiguation... In the future I might make room for gltf3 if/when it is published.

- versioning: initially I plan to go with pre-release semver... But at some point it might be desirable some sort of semi automatic versioning.

- I need to cleanup a bit the materials API

**Comment by vpenades** [comment]
Prerelease package is available [here](https://www.nuget.org/packages/SharpGLTF)

Let me know if you have any issues or questions!

**Comment by promontis** [comment]
Ah man! You are on 🔥 !
It even comes with a nice icon \o/

**Comment by vpenades** [comment]
I've just uploaded a new update of the nuget package, the API still needs a lot of polish, so expect sudden changes from one version to another... hopefully things will settle down over time.

I'll try to track the API changes from one version to another, and setup a sorts of a roadmap and the planning ahead.

Since the nuget has been published, I'm closing this issue... feel free to ask any questions about the API
