### ISSUE TITLE
Extras Encoding

### ISSUE THREAD

**Issue by Zhuangkh** [vpenades/SharpGLTF#100]
I use string dictionary (like {"Hello":"你好"}) to construct JsonContent, and try to skip escaping by setting the Encoder property of JsonSerializerOptions to JavaScriptEncoder.UnsafeRelaxedJsonEscaping.

But when I finally generated the Gltf file, it was still escaped as {"Hello":"\u4f60\u597d"}.

Is there any setting available to solve this problem?😭

**Comment by vpenades** [comment]
Hmmm....   the Extras uses its own encoder so you can interact with the extras at many levels.... BUT....  the glTF writer uses its own encoder.... and right I haven't exposed any json options other than indenting, so right now I don't think it's possible to fix this on your own.

So it's probably a bug on my side; certainly you have to be able to write non ascii characters, so I'll look into it.

**Comment by Zhuangkh** [comment]
Maybe add an Encoder property to WriteSettings?

**Comment by vpenades** [comment]
@Zhuangkh It took a while, but I finally got an answer. It was also specified in the schema, but for some reason I missed it:

https://github.com/KhronosGroup/glTF/issues/1978#issuecomment-831624406

So, on my side, I could truly add json write options to the write settings, so you could enable UTF16 encoding... but then, as per glTF schema,  only ASCII characters are allowed, so adding that feature would allow writing glTFs that could be considered malformed.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding

So, I'm afraid you'll have to bear with escaped encoding: {"Hello":"\u4f60\u597d"}

Since this cannot be resolved, I am closing this issue.

**Comment by vpenades** [comment]
@Zhuangkh Okey, after talking with people from glTF board, I understand writing chinese characters to the json file would be allowed, except for URIs, which would still require escaped characters.

You can find the changes in [this commit](https://github.com/vpenades/SharpGLTF/commit/05d0a5fe63e5433bbf0333ebac86896e73fee41b).

Also, there's a unit test showcasing how to configure the write settings to allow extended characters [here](https://github.com/vpenades/SharpGLTF/blob/4788e4715edffa5fc6a3027950964dd06fa14d13/tests/SharpGLTF.Core.Tests/IO/JsonContentTests.cs#L224-L231).

**Comment by Zhuangkh** [comment]
I have seen the relevant issues discussed.

Thank you for your work!
