### ISSUE TITLE
CurveFactory might need to be public

### ISSUE THREAD

**Issue by emackey** [vpenades/SharpGLTF#107]
Not sure if I've done something wrong, but I can't seem to access CurveFactory from outside SharpGLTF.

https://github.com/vpenades/SharpGLTF/blob/b4e0140ee874abb63c0bfc990c84ad2013935878/src/SharpGLTF.Toolkit/Animations/CurveFactory.cs#L12

Is this supposed to be `public static class CurveFactory` ?

**Comment by vpenades** [comment]
CurveFactory is essentially used to back the functionality of [AnimatableProperty{T}.UseTrackBuilder](https://github.com/vpenades/SharpGLTF/blob/b4e0140ee874abb63c0bfc990c84ad2013935878/src/SharpGLTF.Toolkit/Animations/AnimatableProperty.cs#L130)

You could call CurveFactory indirectly by creating an AnimatableProperty, call UseTrackBuilder, and then discard the AnimatableProperty{T}.

To some degree, AnimatableProperty{T} _is the public API of CurveFactory_.

Notice that, in glTF, the only place you can use curves is in scene Nodes, that's why AnimatableProperty is being used in the appropiate places of NodeBuilder.

The calling hierarchy looks like this:

NodeBuilder -> Translation|Scale|Rotation AnimatableProperty -> UseTrackBuilder -> (internal) CurveBuilder.

**Comment by emackey** [comment]
Aha, user error, perfect.  I switched my code to UseTrackBuilder.  Thanks!
