### ISSUE TITLE
Support meshopt extension

### ISSUE THREAD

**Issue by issacclee** [vpenades/SharpGLTF#109]
Hi @vpenades ,
Just wondering if you have any plans to support loading mesh with meshopt extension?

Thanks!

**Comment by vpenades** [comment]
I would like to support it at some point, yes, I just need to find time to do it.

The extensions itself is not difficult to add the the API.... what's more dificult is to program the encoding/decoding algorythms, which is what will take a while

**Comment by issacclee** [comment]
Hi @vpenades ,
So my use case is, I flagged some nodes by adding extras to it them prior to gltfpack optimizing gltf files. After gltfpack done its thing, it will reorganize the node structures. And I want to use SharpGLTF to load the optimized gltf file to find the new index of those nodes that I flagged before. Would you mind point me to the right direction to simply allow SharpGLTF to parse the gltf without checking if gltf contains meshopt extension?

**Comment by vpenades** [comment]
You can try loading the glTF by disabling all the safety checks, although not sure if it will apply to extensions, it's been a while since I've visited that part of the code.

```c#
var model = ModelRoot.Load( "model.gltf", SharpGLTF.Validation.ValidationMode.Skip );
```

Notice that, if it loads, it will produce a model that is essentially unusable because lots of cross-references, indices, etc, will be wrong.

so you can probably browse through the node hierarchy, as long as you don't access Mesh data, which would trigger a cascade of calls that would result in an exception at some point.

**Comment by vpenades** [comment]
moved to [draco? discussion](https://github.com/vpenades/SharpGLTF/discussions/235#discussioncomment-9368245)
