### ISSUE TITLE
Save methods overloads with Stream input

### ISSUE THREAD

**Issue by electro-logic** [vpenades/SharpGLTF#113]
Hello,

Would be very handy to have some additional overloads for SaveGLB() and SaveGLTF() that accept a Stream as input, to enable additional scenarios. In UWP for example you need to request a permission to get a workable Stream for files and without these override only the LocalApp path is easily usable.

As a temporary workaround I'm using this code

`
var context = WriteContext.CreateFromStream(stream).WithBinarySettings().WithSettingsFrom(null);
context.WriteBinarySchema2("model", model);
`

to "emulate" a model.SaveGLB(stream)

Thank you,
Leonardo

**Comment by vpenades** [comment]
There's already a method to [write a GLB to a a stream](https://github.com/vpenades/SharpGLTF/blob/c3063d9a8888229ac9a27722ee7071e4a9e6c899/src/SharpGLTF.Core/Schema2/Serialization.WriteSettings.cs#L249).

Notice there's no counterpart for glTF because an open glTF file writes multiple files, and those cannot be written to a single stream.

For advanced scenarios, you can check the example that writes [glTFs to a ZIP](https://github.com/vpenades/SharpGLTF/blob/master/src/SharpGLTF.Toolkit/IO/Zip.cs) file (which is a stream)

**Comment by electro-logic** [comment]
Thanks a lot for the quick reply, I missed that because of the different name.

Why not moving (or adding) it to an overload of the SaveGLB method? Would be an easier API.

Thanks again

**Comment by vpenades** [comment]
It's a personal naming convention.  I use `Load/Save`  for system files,  and `Read/Write`  for streams, arrays, and essentially anything that is not a file.

**Comment by electro-logic** [comment]
Make sense, thanks again
