### ISSUE TITLE
Please make a Unity3d compatible version release

### ISSUE THREAD

**Issue by EgoInc** [vpenades/SharpGLTF#124]
Seems like system.text.json does not work at all with modern Unity3d projects. Could you please create a unity3d demo (with Unity3d compatible versions of DLLs)?

**Comment by vpenades** [comment]
The problem is not only system.text.json, it's all the Span<T> that are spread across all the code. Simply put, it would take too much time to redesign.

In fact, I am aware that unity 3D is working towards supporting net6, which is compatible with system text json

Simply put, it will take less time for unity to catch up and be compatible, than me redesigning the library, so by the time I had finished the redesign, it would have become a waste of time.
