### ISSUE TITLE
Embedded texture

### ISSUE THREAD

**Issue by Omega1975** [vpenades/SharpGLTF#129]
Hi, I'm export a model with texture in glb format. But the texture are not embeded. Where am I doing wrong ?
Below are the instructions I use

WriteSettings ws = new WriteSettings();   
ws.JsonIndented = true;
ws.ImageWriting = ResourceWriteMode.Embedded;
model.SaveGLB(filename, ws);

**Comment by vpenades** [comment]
Hi

Two separed things here:

Alpha25 of the library has a bug that fails to embed the texture in the binary, it's already fixed in the source code; you can try cloning the repo and referencing the project directly until new nugets have been released (soon)

You don't need to set all the writesettings for GLB, simply SaveGLB(filename) does the thing.

**Comment by Omega1975** [comment]
Great! it works
