### ISSUE TITLE
System.ArgumentException: M44 (Parameter 'M44 0.9999999 must be equal to 1.')

### ISSUE THREAD

**Issue by ninichki** [vpenades/SharpGLTF#150]
Hi,
i set worldMatrix of a child node:
![image](https://user-images.githubusercontent.com/1086380/191295977-52d01bd4-9769-4018-b36d-58f6d09d035e.png)
then I get following error:
 System.ArgumentException: M44 (Parameter 'M44 0.9999999 must be equal to 1.')

My values are:
![image](https://user-images.githubusercontent.com/1086380/191296133-948bcf46-4d59-40e8-b4d8-82a6489310f2.png)
and
![image](https://user-images.githubusercontent.com/1086380/191296179-d05ea06b-d516-4288-abf4-2b6b74eb2860.png)

That should give me a matrix with 0 0 0 1 last row.

**Comment by vpenades** [comment]
I assume you're setting the world matrix of a child node.

glTF nodes don't have a world matrix, only a local matrix.

The World Matrix property exposed by SharpGLTF is built from the local matrices of the node chain.

In order to set the world matrix of a child node, internally, the library calculates the INVERSE matrix of the parent node, and multiplies it by the matrix you're setting. This is how the local matrix of the child node is evaluated. Most probably, there's some precission lost in these calculations and, since glTF specification does not allow any value other than 1, it throws an error.

I might look at it to see if I can handle this use case; in the meantime, instead of setting the world matrix, do the math steps yourself with the local matrix, fix the m44 to 1, and set the local matrix of the child node.

**Comment by ninichki** [comment]
The only place i'm setting the worldmatrix is here 
![image](https://user-images.githubusercontent.com/1086380/191428650-ce8bbed2-2a77-40d7-bf5f-c882ede41a49.png)

**Comment by ninichki** [comment]
Matrix4x4.Invert(parentMatrix, out Matrix4x4 invertedParentMatrix)

![image](https://user-images.githubusercontent.com/1086380/191468769-9721568b-359e-4b1f-bda7-2aaef7e9058d.png)
resolves to:
![image](https://user-images.githubusercontent.com/1086380/191468931-af801641-06db-48ad-ad80-37d11a89d7b2.png)

**Comment by vpenades** [comment]
Can you dump your (the non inverted) parent matrix to bytes?

you can use System.BitConverter  to get the bytes from a float.

**Comment by vpenades** [comment]
It should be fixed in the Alpha 27 nuget packages.
