### ISSUE TITLE
[Feature Request] Mesh Smoothing

### ISSUE THREAD

**Issue by dale-personal** [vpenades/SharpGLTF#185]
Perhaps this functionality already exists and i wasn't able to find it, but here goes:

Looking for the ability to "smooth" a mesh. Also also referred to as "force shared vertices" or minimize vertices.

Here is a link to the implementation in babylon.js:

https://doc.babylonjs.com/toolsAndResources/utilities/Minimise_Vertices

**Comment by vpenades** [comment]
To some degree, it's what MeshBuilder does...  but you need to have the normals precalculated in advance.

Notice that BabylonJS es a full 3D framework whereas SharpGLTF _is just a file format_...  So I try to avoid responsabilities that exceed importing/exporting glTF models.

Having said that, _I did tried to calculate the normals of a meshbuilder that were missing them_ , but I couldn't complete the task because MeshBuilder also supports morph targets, and calculating normals for mopth targets is exceedingly complex.. so this feature is not available.

My suggestion is to calculate the normals beforehand (it's not too difficult) and then feed them to a MeshBuilder... and at that point, _MeshBuilder does the vertex welding_.
