### ISSUE TITLE
[QUESTION] Could you please help me with fixing the model viewer rendering issue in the code?

### ISSUE THREAD

**Issue by nikeruga** [vpenades/SharpGLTF#197]
"I apologize for the initial inquiry about a different library. If it violates the policy, feel free to delete the post. I am having difficulty using the SharpGLTF library, so I am creating a viewer with the glTF-CSharp-Loader library instead. Could you please assist me? Thank you."

"I have written code to load and viewer a file, but the model viewer displays shapes differently.
I am not sure if there is an issue with point transformation or binary processing.
In Eyeshot, it seems there might be a problem with the 'normals' generation part of the point creation code, but I am uncertain if there is an error in my code.
My code is available at the following link, so please take a look and provide assistance. Thank you."

https://drive.google.com/file/d/1ZLmjOLyYnJXXtcyAd9TDPMsIgQ2ReW3-/view?usp=sharing

eyeshot answer:
The index error, in this case, happens when accessing the mesh normals array.
 You are probably assigning them wrong.
Depending on the nature type of the mesh, the number of normals differs a lot.
See: natureType Enumeration.
 Commenting the normals assignment out already works for your code:
//nodeMesh.Normals = nodeMeshNormals.ToArray();
 Since eyeshot can calculate the mesh normals by itself, consider skipping them during the reading if possible.

![OriginShip](https://github.com/vpenades/SharpGLTF/assets/39543900/da0221bc-dbe7-4c93-98ad-3d7199b0a155)
![ConvertShip](https://github.com/vpenades/SharpGLTF/assets/39543900/bdb3c37e-e897-4f33-8421-a345753cded9)
![ConvertShip_what](https://github.com/vpenades/SharpGLTF/assets/39543900/27b234d8-7ce6-424f-89fe-dd1c7fed1a06)

**Comment by vpenades** [comment]
SharpGLTF has an extension method that allows exporting the model to Wavefront OBJ. This method is designed to capture a snapshot of the actual geometry stored in the model, so it can be used to debug and diagnose the contents of a glTF

So, you can try loading the model in sharpGLTF, and then use the extension method to export it to Wavefront OBJ.

If the exported wavefront OBJ still looks wrong, then the problem is, most probably, _in the source model you're trying to import_.

If the wavefront OBJ looks fine, then the problem is, most probably, in the model viewer, which is not correctly interpreting the glTF node transforms.

**Comment by nikeruga** [comment]
"The model file I used has been thoroughly validated in PixyzStudio. It seems there might be an issue with my code. I'm stuck here. If you have time, could you please take a look at the attached project in the link?"

**Comment by vpenades** [comment]
At first sight of your code, it would take me a few hours to review your code in order to find the issue, and probably more to offer a solution, which is beyond what can I do in my spare time for free.

If you want me to dig deep into your code, I think you might consider purchasing a one time 50$ sponsorship so I can justify expending that amount of time one your code

**Comment by nikeruga** [comment]
"Thank you for your kind reply. I think I might stop here as this is just at a learning level. It's not easy..."

**Comment by vpenades** [comment]
I understand;  glTF is very complex file format, and I tried to make the library as easy to use as possible... but at the end it's still a very complex format and it's the responsability of the end developer to deal with these difficulties.

If you want to keep looking into glTF rendering on your own, I would suggest you to look into this other library:

https://github.com/vpenades/SharpGLTF/tree/master/src/SharpGLTF.Runtime

SharpGLTF.Runtime does not do the rendering, but it prepares the model to make it easier to integrate into other rendering engines.
