### ISSUE TITLE
FileLoadException in Navisworks plug-in

### ISSUE THREAD

**Issue by StepanovGM** [vpenades/SharpGLTF#223]
Hello!

I am using SharpGLTF for my navisworks exporter project and I've ran into an error:

When i try to use SharpGLTF inside navisworks plugin i get fatal error and navisworks crashes. dmp file shows, that my plug-in tries to load System.Numeric.Vectors version 4.1.3.0 and fails.  I can't understand why it tries to load this version, considering SharpGLTF uses version 4.1.4.0 of this library, which I added to naviswork dependencies folder.

I found similar issue (https://github.com/vpenades/SharpGLTF/issues/4) and tried everything discussed there, but nothing changed.

I am not sure if it's a bug or an error on my side, and would appreciate any help ☺

**Comment by vpenades** [comment]
I suspect your target framework is Net47x or Net48, right?  because there are the only ones giving problems with System.Numerics.Vectors

I don't fully understand the problem, but basically the conflict happens when multiple libraries try to use different versions of the same package.

Theoretically, the highest version should be picked, but some libraries (not sharpGLTF) explicitly require a specific version, preventing other libraries to work correctly.

The only solution I can provide is for you to clone the project, change the version to the one you need, and compile a custom package tailored to the version you require.

Another solution would be to re-introduce net48 as a target framework which, I think, has in-built support for system.numerics and does not require referencing the package.

**Comment by StepanovGM** [comment]
Thank you for your answer!

Yes, you are right, target framework is Net4.7

I will try compiling my own version, hope it will work

**Comment by StepanovGM** [comment]
Hello, for anyone wondering how to fix simmilar issue;
The problem was that i changed config of my app, but not of Navisworks. After i added these lines to Navisworks' Roamer.exe.config everything worked.
```
<dependentAssembly>
            <assemblyIdentity name="System.Numerics.Vectors" 
                              publicKeyToken="b03f5f7f11d50a3a" 
                              culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.3.0" 
                             newVersion="4.1.4.0" />
         </dependentAssembly>
```

Another (i think more preferable) way is to add ResolveEventHandler in code. I've put it in my class constructor.
```
public MyClass() 
{
    AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve);
}
Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
{
    var name = new AssemblyName(args.Name);
    if (name.Name == "System.Numerics.Vectors")
    {
        return typeof(System.Numerics.Vector).Assembly;
    }
    else if (name.Name == "System.Runtime.CompilerServices.Unsafe")
    {
        return typeof(System.Runtime.CompilerServices.Unsafe).Assembly;
    }
    //you can add any conflicting assembly the same way
    return null;
}
```
