### ISSUE TITLE
Add Skin `GetJoints` API

### ISSUE THREAD

**Issue by ptasev** [vpenades/SharpGLTF#244]
There's currently no way to get all of the joints in a skin (either as logical indices or as nodes). You have to loop joints count and call GetJoint(int index) instead. This incurs the cost of generating the IBM when it is not necessary. The request is to add an API to access the joints.

For reference, my use case is that I'm trying to convert an entire scene as a single skinned mesh and skeleton. Right now I'm using `UnsafeAccessor` to get the joints. Here's my code:
```csharp
List<int> GetJoints(Skin skin)
{
    return GetJointsField(skin);
    
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_joints")]
    extern static ref List<int> GetJointsField(Skin skin);
}

var skinnedMeshNodes = Node.Flatten(scene).Where(x => x.Mesh is not null && x.Skin is not null).ToArray();
var skinRoots = skinnedMeshNodes
    .SelectMany(x => GetJoints(x.Skin).Select(idx => x.LogicalParent.LogicalNodes[idx].VisualRoot)).Distinct();
var skeletonNodes = skinRoots.SelectMany(Node.Flatten).Distinct();
```

**Comment by vpenades** [comment]
One of the ideas behind GetJoint was to point that a skin joint needs both a node transform and an IBM, so there's no way to get one without the other. That alone is important because most developers rush to get the node transforms without paying attention to the IBMs. Actually, many developers don't even know the purpose of the IBMs, so to some degree, the design of the API is a way to tell "look, here there's something you must pay attention to"

Obviously that's not your case, but I wanted to explain the reason why the API is designed the way it is.

Having said that, if you think it's worth to you, I can add an additional method to retrieve the joints without calculating the IBMs

Now, I wonder if you want a  `IReadOnlyList<Node> GetJoints();`  or a `IReadOnlyList<int> GetNodesLogicalIndices();`

**Comment by ptasev** [comment]
Makes sense, but I wonder how much coddling is necessary from the library.

I think returning the node instances makes the most sense.

**Comment by vpenades** [comment]
I'll look into it; I might go for nodes... no array allocation needed.
