### ISSUE TITLE
Writing gltf file (ModelRoot.Save) is slower after updating to version 17 from version 15

### ISSUE THREAD

**Issue by AhmedMakhlouf** [vpenades/SharpGLTF#53]
Saving a specific gltf file (55MB) takes 2.3 mins using version 15, writing the same file in version 17 took 5 mins (with or without WriteSettings.Validation)

**Comment by vpenades** [comment]
hmmm.... 55mb is quite a lot....   could it be possible to share the model? or send it to me privately?

**Comment by AhmedMakhlouf** [comment]
I can share it with you privately

**Comment by vpenades** [comment]
you can write me at vpenades@gmail.com

**Comment by vpenades** [comment]
I can reproduce the issue, and I've found the problem happened between version 15 and 16... I'll continue investigating...

**Comment by vpenades** [comment]
Okey, this is what I found so far:
- The current development branch (master) has the SkipValidation fixed, so, if you're in a hurry, you could clone the repository and compile it, at least until I release a new version of the library (in one or two weeks)
- The increased load/save time seems to be due to some more strict hierarchy validation checks. Given that there's 40.000 nodes in the scene (wow!), it makes sense it takes a while to traverse the whole tree.

I'll see if I can add some optimizations to the validation code... but I guess you want to load/save fast, which can be solved with the SkipValidation in the next version.

**Comment by AhmedMakhlouf** [comment]
Thanks a lot for the effort, we will wait for the stable version. Looking
forwards

Kind regards
*Ahmed Makhlouf*
Game Developer
Tel: (+20) 1096465010

**Comment by vpenades** [comment]
Version 18 is up, let me know if it solves yout problem.
