### ISSUE TITLE
Duplicate Materials on Export

### ISSUE THREAD

**Issue by tomspilman** [vpenades/SharpGLTF#54]
On creating the meshes we're careful to share `MaterialBuilder`s when creating meshes.  We basically have one material per-texture.  Later when we export we find duplicate materials with the same name...

![image](https://user-images.githubusercontent.com/103522/85187015-0fcf3b80-b262-11ea-83ca-696f4c75e5ba.png)

Is there a way to keep it from doing this?

**Comment by tomspilman** [comment]
@vpenades - I hack things by doing this:

![image](https://user-images.githubusercontent.com/103522/85187265-f0391280-b263-11ea-9513-73add3eaa534.png)

... but likely that is a bad solution.

The issue is each call i make to add a mesh to a node looks like this:

`node.WithMesh(root.CreateMesh(mesh));`

... each of these calls can end up creating duplicate materials in the `ModelRoot` as it never checks if the material already exists.

**Comment by vpenades** [comment]
The Schema2 namespace creation methods are quite explicit, and are expected that you build some minimum infrastructure over them.

I would suggest you to use Toolkit's SceneBuilder to build your scene. because it has a number of advantages over writing the glTF Schema2 DOM yourself:

- SceneBuilder is easier to edit and manipulate than the glTF DOM.
- When converted to glTF Schema2 DOM it is able to apply some optimizations:
  - It finds shared MaterialBuilders and reuse them.
  - It finds shared meshes and reuse them.
  - Meshes with identical vertex attributes are concatenated so they use the same vertex/index buffers
  - When converting to Schema2.glTF you can choose between strided vertex buffers, or a vertex buffer per vertex attribute.

If you're worried about using SceneBuilder, it has pretty much all the features supported by vanilla glTF, and I have some roundtrip tests that demonstrate how to convert a glTF2 to SceneBuilder and back to glTF

Actually.... in order to collapse shared materials, A good solution would be to convert your glTF to SceneBuilder, and back to glTF to benefit from the SceneBuilder's optimizations.

**Comment by tomspilman** [comment]
> That's why there's also a root.CreateMeshes(...);
> CreateMeshes is able to find all the shared materials in the input meshes and coalesce them.

I see... so my mistake is not building all the meshes in one call... then after that doing the node association.

> Anyway, I would suggest you to use Toolkit's SceneBuilder to create your meshes;

I didn't realize i wasn't using the recommended path.  There seems to be several ways to do things and not every clear guidance as to which way is best.

Thanks for clearing this up!
