### ISSUE TITLE
Make BinarySerialization public?

### ISSUE THREAD

**Issue by koliyo** [vpenades/SharpGLTF#60]
The `BinarySerialization` class has some useful utilities that I would like to be able to use externally, especially `BinarySerialization._Identify(stream)` to check if stream is binary or ascii.

Now I had to copy the code to be able to call it from external namespace.

**Comment by vpenades** [comment]
I would really preffer to keep that class internal, because it gives me room for refactoring without breaking any API.

The reading/wrinting APIs are located in the generar reader/writer classes, so it could be possible to expose that functionality there.

Understanding what you want to do would give me a better understanding of what you need.

**Comment by vpenades** [comment]
I've added this static method: `SharpGLTF.IO.ReadContext.IdentifyBinaryContainer`
