### ISSUE TITLE
Callback Image loader

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [vpenades/SharpGLTF#73]
Hi !

I was wondering if it exists a way to have a callback when an image is loading (with the path as an argument).
Obviously, I tried to use ReadSettings.ImageReader callback, but it's called once the uri is checked, so in case of wrong path (with an extra folder name or a folder name missing for example), then, it's too late to try to find the texture file on disk. 

Thanks in advance, and thanks for the great work !

Eric

**Comment by vpenades** [comment]
hmmm.. it would be difficult to inject a callback so early, because the json loading, parsing, validation and uri escaping/unescaping are pretty much tied toghether.

Consider that any invalid or wrong texture path renders the whole glTF as invalid.

could you provide an example of the file you want to load?

**Comment by EricBeetsOfficial-Opuscope** [comment]
Hi Vicente,

Perfect, it works ! It was exactly that I need !
Thank you for your help !

Eric
