### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by FSandner** [vpenades/SharpGLTF#84]
Hi, we are using SharpGLTF for converting internal 3D Modeldata to glb.
Now we came to the problem, that large model data creates too large glb files. 
Is there a possibility to split it into different chunks?
or how can i evaluate size of MESH or NODES before i add it to  the ModelRoot.
Thanks for answer
Fritz

**Comment by vpenades** [comment]
Without making modifications to the library, the solution that comes to mind is this:

Don't use SceneBuilder,  use MeshBuilder to create your individual meshes.

Then, Add the MeshBuilders to a ModelRoot object, _one by one_ using the [CreateMesh](https://github.com/vpenades/SharpGLTF/blob/67dc466c586bfc5d2889e75d85a97dc9845980ed/src/SharpGLTF.Toolkit/Schema2/MeshExtensions.cs#L19) extension. Internally, this will create new independent buffers for every mesh you add.

Finally, when saving your model, save it as glTF, NOT as GLB, and be sure to pass the WriteSettings property with [MergeBuffers](https://github.com/vpenades/SharpGLTF/blob/67dc466c586bfc5d2889e75d85a97dc9845980ed/src/SharpGLTF.Core/Schema2/gltf.Serialization.Write.cs#L77) set to false.

If I did not forget anything else, this will do the trick.

**Comment by FSandner** [comment]
Hi, i can't use gltf.
But i found different problem. When i use CreateMesh one by one with same MaterialBuilder object, these Materials will be duplicated in ModelRoot.LogicalMaterials.
Is there a possibility to avoid this?

**Comment by vpenades** [comment]
Yes, by using [CreateMesh with material evaluator](https://github.com/vpenades/SharpGLTF/blob/67dc466c586bfc5d2889e75d85a97dc9845980ed/src/SharpGLTF.Toolkit/Schema2/MeshExtensions.cs#L24).

You can pass a lambda that wraps a dictionary of materials, so instead of reprocessing already existing materials, you can pass the materials previously cached... you can find that lambda implementation [here](https://github.com/vpenades/SharpGLTF/blob/67dc466c586bfc5d2889e75d85a97dc9845980ed/src/SharpGLTF.Toolkit/Schema2/MeshExtensions.cs#L43-L49)

Why you can't use gltf? a GLB can only contain a single buffer. if you want to write multiple buffers, that leaves a GLB with just a single json inside... in this case scenario, a GLB is not giving any benefit.

**Comment by FSandner** [comment]
do you have an example for the usage of material Evaluator?

**Comment by vpenades** [comment]
You just copy the lambda I've linked in my previous post, and pass it as an argument to the CreateMesh method.

**Comment by FSandner** [comment]
👍 material evaluator is working.
back to first question....
can i estimate size of glb before i use ModelRoot.WriteGLB()

**Comment by vpenades** [comment]
I think this:
```c#
var totalSize = ModelRoot.LogicalBuffers.Sum(buffer => buffer.Content.Length);
```
would give a good estimate of the total size of the file.
